In [1]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

In [2]:
# 60000 image  (28*28) , ytranin =10000 image
(x_train, y_train),(x_test, y_test) = mnist.load_data()
print('X Train Shape is : ' , x_train.shape)    
print('X Train  is : ' , x_train[5])
print('---------------------------------------- ')
print('X Test Shape is : ' , x_test.shape)
print('X Test  is : ' , x_test[5])
print('---------------------------------------- ')
print('y Train Shape is : ' , y_train.shape)
print('y Train is : ' , y_train[5])
print('---------------------------------------- ')
print('y Test Shape is : ' , y_test.shape)
print('y Test  is : ' , y_test[5])

11490434/11490434 [==============================] - 0s 0us/step
X Train Shape is :  (60000, 28, 28)
X Train  is :  [[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  13  25 100
  122   7   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0  33 151 208 252 252
  252 146   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  40 152 244 252 253

In [3]:
print(x_train)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [4]:

model = tf.keras.models.Sequential()

In [5]:


model.add(tf.keras.layers.Flatten())

In [6]:

model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
# activation =  softmax  , elu , relu , tanh , sigmoid , linear

In [7]:


model.add(tf.keras.layers.Dropout(0.2))

In [8]:

model.add(tf.keras.layers.Dense(10, activation=tf.nn.softmax))

In [9]:


model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [10]:

model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 2.1884 - accuracy: 0.7541
Epoch 2/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5657 - accuracy: 0.8527
Epoch 3/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.4711 - accuracy: 0.8758
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4097 - accuracy: 0.8954
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3892 - accuracy: 0.8995
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3675 - accuracy: 0.9059
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3488 - accuracy: 0.9123
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3375 - accuracy: 0.9159
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3325 - accuracy: 0.9184
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.326

In [11]:

output = model.predict(x_test)

313/313 [==============================] - 1s 2ms/step


In [ ]:

#
output[0]

array([0.0000000e+00, 1.3922033e-21, 2.9038399e-12, 1.2124548e-13,
       2.2126604e-18, 1.3526520e-22, 0.0000000e+00, 1.0000000e+00,
       0.0000000e+00, 1.0524449e-17], dtype=float32)

In [ ]:
#

import numpy as np
y_pred=np.argmax(output,axis=1)

In [ ]:
print(y_pred)

[7 2 1 ... 4 5 6]


In [ ]:
import numpy as np

In [ ]:
y_pred=

In [ ]:
y_pred

7

In [ ]:
val_loss, val_acc = model.evaluate(x_test, y_test)

10000/10000 [==============================] - 2s 217us/sample - loss: 5.8991 - acc: 0.6330


In [ ]:
# بيسيف  الويت اللي انا لسه م\رباها
model.save('1.model')

In [ ]:
new_model = tf.keras.models.load_model('1.model')

In [ ]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                    tf.keras.layers.Dense(128, activation=	tf.nn.relu),
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
                                   ])